version: '3.7'

services:
  db:
    image: mariadb:10.4
    restart: always
    env_file:
      - db.env

  pyarcade:
    build:
      context: .
    depends_on:
      - db
    environment:
      - FLASK_APP=pyarcade/api:create_app()
      - FLASK_ENV=development
    ports:
      - 5000:5000
    # Use a long timeout to accomodate various machines. Use the strict option
    # so that the command is not run if the polling fails.
    command: wait-for-it.sh db:3306 -t 60 -s -- flask run --host=0.0.0.0
