version: '3.7'

services:
  db:
    image: mariadb:10.4
    env_file:
      - db.env

  pyarcade:
    depends_on:
      - db
    build:
      context: .
      dockerfile: pyarcade-browser-test.Dockerfile
    environment:
      - FLASK_APP=pyarcade/start
      - FLASK_ENV=development
    command: wait-for-it.sh db:3306 -t 30 -s -- python setup.py test
